apiVersion: batch/v1
kind: Job
metadata:
  name: curl-job-service
  labels:
    app: curl-job-service
spec:
  template:
    spec:
      containers:
      - image: curlimages/curl
        command: ["/bin/sh", "-c", "--"]
        args: ["curl -s -f --connect-timeout 5 http://webserver"]
        name: curl
      restartPolicy: Never
