apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver-rc
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: nginx:1.20.1
        ports:
        - containerPort: 80